### PR TITLE
PLASMA update to 21.8.29

### PR DESCRIPTION
**Pull request by jcsiadal**
Signed-off-by: jcsiadal <jeremy.c.siadal@intel.com>

Updates the PLASMA package from 2.8.0 to 21.8.9. All of the Python scripts are migrated to Python3.
For some reason the source tarball doesn't include the lua source in the plasma git tree. I removed it from the makefile and use the distro-provided Lua instead.
Here-doc module converted to native Lmod lua.

Arm builds need to be validated, as I don't have access to Arm systems to check the compiler options.

### CODE REVIEW

**Comment by adrianreber** [comment]
Please rebase. I fixed the CI errors.

**Comment by adrianreber** [comment]
Now it says: `doxygen: Command not found`. This seems a real error.

**Comment by adrianreber** [comment]
To fix the RHEL build failure maybe something like CC=gcc is needed during `make install`. The Leap failure is the same problem as with boost. Somehow the PATH is broken and lmod cannot correctly handle it.

**Comment by jcsiadal** [comment]
CC is already explicitly set in OHPC_setup_compilers. I suspect we're going to hit these same issues with a lot of component updates and I'd like to fix the core issue.

**Comment by adrianreber** [comment]
If you squash the fixup commit in the first one this is ready from my point of view.

**Comment by jcsiadal** [comment]
All commits squashed.

**Pull request merged**
