### PR TITLE
Issue 178

### PR DESCRIPTION
**Pull request by surak**
commit 17000841623b012102f4de2f6f54bfdbbeaa1604

### CODE REVIEW

**Comment by surak** [comment]
Commit #6e1fdc2

**Comment by surak** [comment]
Ping

**Comment by koomie** [comment]
Sorry for the delay - will get back to the cube work a bit later this week....

**Comment by surak** [comment]
Any news? It still shows as open....

**Comment by koomie** [comment]
Doh, sorry I dropped the ball on that. I merged onto the issue_178 branch.

**Pull request closed without merging**
