### PR TITLE
dev-tools: Adapt all pkgs for openEuler

### PR DESCRIPTION
**Pull request by Yikun**
- Add make as autoconf/cmake BuildRequires
- Adapt openEuler 22.03

Signed-off-by: Yikun Jiang <yikunkero@gmail.com>

### CODE REVIEW

**Comment by Yikun** [comment]
https://github.com/openhpc/ohpc/actions/runs/3926755349/jobs/6712765363

autoconf error:
```
+ make -j2 DESTDIR=/home/ohpc/rpmbuild/BUILDROOT/autoconf-ohpc-2.69-19999.ci.ohpc.x86_64 install
/var/tmp/rpm-tmp.Q7GdnC: line 39: make: command not found
error: Bad exit status from /var/tmp/rpm-tmp.Q7GdnC (%install)

RPM build errors:
    Bad exit status from /var/tmp/rpm-tmp.Q7GdnC (%install)
```

cmake error:
```
Error when bootstrapping CMake:
Cannot find appropriate Makefile processor on this system.
Please specify one using environment variable MAKE.
```

Solved: Added `make` as buildrequires

**Comment by Yikun** [comment]
```
autom4te_perllibdir='..'/lib AUTOM4TE_CFG='../lib/autom4te.cfg'         ../bin/autom4te -B '..'/lib -B '..'/lib         --language M4sh --cache '' --melt ./autoconf.as -o autoconf.in
chmod +x autoupdate.tmp
chmod a-w autoupdate.tmp
mv autoupdate.tmp autoupdate
Can't locate File/Compare.pm in @INC (you may need to install the File::Compare module) (@INC contains: ../lib /usr/local/lib64/perl5/5.32 /usr/local/share/perl5/5.32 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5) at ../lib/Autom4te/FileUtils.pm line 166.
BEGIN failed--compilation aborted at ../lib/Autom4te/FileUtils.pm line 166.
Compilation failed in require at ../bin/autom4te line 40.
BEGIN failed--compilation aborted at ../bin/autom4te line 40.
make[2]: *** [Makefile:641: autoconf.in] Error 2
make[2]: Leaving directory '/home/ohpc/rpmbuild/BUILD/autoconf-2.69/bin'
make[1]: *** [Makefile:357: install-recursive] Error 1
make[1]: Leaving directory '/home/ohpc/rpmbuild/BUILD/autoconf-2.69'
make: *** [Makefile:673: install] Error 2
error: Bad exit status from /var/tmp/rpm-tmp.SlGo3f (%install)
```

`autoconf` failed on `CentOS Stream 9`: https://github.com/openhpc/ohpc/actions/runs/3926924304/jobs/6713084292#step:7:419 

Any idea? @adrianreber Looks like need more buildreuqires?

**Comment by adrianreber** [comment]
You could try with `BuildRequires: perl(File::Compare)`.

**Comment by adrianreber** [comment]
I think there are tests for cmake, autotools and spack in the test suite. Changes to these spec files should trigger the corresponding tests. Can you also adapt the mapping file to trigger those tests, please.

**Comment by martin-g** [comment]
@Yikun is on holidays and I cannot update his branch/PR, so I opened a new one - https://github.com/openhpc/ohpc/pull/1663

**Comment by Yikun** [comment]
Replaced by https://github.com/openhpc/ohpc/pull/1663

**Pull request closed without merging**
