### PR TITLE
EasyBuild 3.8.1

### PR DESCRIPTION
**Pull request by boegel**

### CODE REVIEW

**Comment by boegel** [comment]
@adrianreber: EasyBuild 3.8.1 is out now, shall I update this in-place or open a new PR?

**Comment by adrianreber** [comment]
Just force push.

**Comment by boegel** [comment]
@adrianreber done!

**Comment by adrianreber** [comment]
Thanks. Looks good. I think I cannot merge PRs, so @koomie @crbaird please merge.

Fixes: #893

**Comment by koomie** [comment]
Thanks for the update. Landed and builds completed successfully:

https://build.openhpc.community/package/show/OpenHPC:1.3:Update7:Factory/easybuild

**Pull request merged**
