### PR TITLE
Lmod update for OpenSUSE 15

### PR DESCRIPTION
**Pull request by jcsiadal**
This updates the Lmod component and its required distros to add OpenSUSE 15 support. I included the preliminary changes for RHEL 8.

Summary of changes:
- Since it's used by multiple specfiles, the luaver assignment is moved to OHPC_macros
- Dropped conditionals for SLES before SP3
- Removed the lua-bit component. Nothing supported depends on it anymore.
- Add support for Lua 5.3.

Basic testing done on SLES12SP4, OpenSUSE 15.1, and CentOS 7-1810.

I got rid of conditional conflicts. I can install SUSE-built environment-modules and I assume this should be still be a conflict. Similarly, I can get Modules for CentOS.

SUSE provides Lua packages in its SLE developer language repo. It's possible to eliminate all extra lua packages in favor of those provided by the distro. Just for consideration.

I didn't update Lmod source. It gets updated every 1 or 2 weeks, and occasionally several times in a day. Someone more savvy with its development cycle should pick the right target version.

### CODE REVIEW

**Comment by adrianreber** [comment]
You found a bug in out travis scripts, but thankfully @amblakem already fixed it in #1006. Once #1006 is merged it would be good to rebase this PR.

**Comment by jcsiadal** [comment]
Rebased. I also fixed a mistake in not checking luaver before setting it. Best practice is to permit override if using rpmbuild manually.

**Comment by jcsiadal** [comment]
Additional changes made to OHPC_macros. Updates Python to 3.6 for RHEL7, RHEL8, and SLE15. Also includes changes from Adrian's update for RHEL8.

**Comment by jcsiadal** [comment]
Closing. Moved all changes to PR1023.

**Pull request closed without merging**
