### PR TITLE
Upgrade ipmiutils to 3.1.8

### PR DESCRIPTION
**Pull request by huangtianhua**
Signed-off-by: huangtianhua <huangtianhua@huawei.com>

### CODE REVIEW

**Comment by adrianreber** [comment]
Thanks for you PR, but I am closing this as OpenHPC no longer ships ipmiutils. It is still in our repository but it was never built for the 2.x branch.

**Comment by huangtianhua** [comment]
I proposed this because ipmiutils built error on enviromment which openssl is 1.1.1m, if community has no plan to upgrade, I will make a patch to fix this, thank you.

**Comment by adrianreber** [comment]
> I proposed this because ipmiutils built error on enviromment which openssl is 1.1.1m, if community has no plan to upgrade, I will make a patch to fix this, thank you.

OpenHPC does not built ipmiutils at all. It is an old package. Why do you build it? Do you need it for openeuler?

**Comment by huangtianhua** [comment]
@adrianreber ,
OK, thanks! 
And so we just have to adapt the packages for whole scope as https://github.com/openhpc/ohpc/blob/2.x/misc/obs/config.2.x#L35  right?

**Comment by adrianreber** [comment]
> @adrianreber , OK, thanks! And so we just have to adapt the packages for whole scope as https://github.com/openhpc/ohpc/blob/2.x/misc/obs/config.2.x#L35 right?

Right. That file lists the packages which are actually built. You can also look at https://obs.openhpc.community/

**Comment by huangtianhua** [comment]
Sorry, I distrub you again, https://github.com/openhpc/ohpc/blob/2.x/misc/obs/config.2.x#L35 only show the packages which are updated in 2.6? But IIUC we have to adapt all ohpc packages(the spec files on 2.x) on openEuler, not only updated in 2.6 ? So if there is a list for all packages we have to adapt?

**Comment by adrianreber** [comment]
You have to look at the 2.6 section and at all previous sections. Maybe something like this would also help: `dnf --available --disablerepo='*' --enablerepo='OpenHPC' --enablerepo='OpenHPC-updates' list`

That should give you an overview of all packages available for the 2.x release branch.

Maybe also this command: ` dnf --disablerepo='*' --enablerepo='OpenHPC' --enablerepo='OpenHPC-updates' repoquery --srpm --qf  '%{NAME}'`.

This would be without 2.6. Once 2.6 is released those commands should also include all packages for 2.6.

**Pull request closed without merging**
