### PR TITLE
Remove Clush and Shine

### PR DESCRIPTION
**Pull request by jcsiadal**
Cleaning up the build tree. This removes more packages that are no longer part of the distro. As with Singularity, the unit tests are left intact.

Signed-off-by: jcsiadal <jeremy.c.siadal@intel.com>

### CODE REVIEW

**Comment by thiell** [comment]
Hi @jcsiadal,
I am maintaining clustershell for openSUSE and I believe clustershell is quite popular in openhpc. What do you mean by no longer part of the distro? 
https://build.opensuse.org/package/show/openSUSE:Factory/clustershell
We recently fixed a packaging issue for Python 3.10, maybe that is related?
Let me know if I can be of any help.

**Comment by jcsiadal** [comment]
I was referring to the OpenHPC distro; I'll be more specific in future PRs. In general, when Red Hat and SUSE distributions include current versions of a package, it will be removed from OpenHPC.

**Comment by adrianreber** [comment]
@utdsimmons This one works for me. Do you want to bring it up in the TSC.

**Comment by jcsiadal** [comment]
Will rebase and submit separately..

**Pull request closed without merging**
