### PR TITLE
Enable slurmd for Rocky/Warewulf/Slurm/2.x Issue #1821

### PR DESCRIPTION
**Pull request by middelkoopt**
Enable slurmd for Rocky/Warewulf/Slurm Issue #1821

### CODE REVIEW

**Review by martin-g — APPROVED** [review]

**Comment by adrianreber** [comment]
Sorry for the long time not reacting. Can you bring this to 2x and 3.x and for all OSes and arches?

**Comment by middelkoopt** [comment]
Rebased patch against 2.x

**Comment by middelkoopt** [comment]
Patch applied to all OS/Arch combo's for 2.x branch and force pushed.

**Comment by middelkoopt** [comment]
Patches applied to 3.x and in PR #1939

**Comment by adrianreber** [comment]
The steps.tex.orig probably can be removed. @martin-g is currently working on a PR to also build the documentation during a PR. Once that is ready and merged I would ask you to rebase the PR for the 3.x branch. If that works we will merge the 2.x PR (this one).

**Comment by middelkoopt** [comment]
Oops. Missed that orig file.  Forced pushed a new commit with that file removed.  Will await notification for rebase for 3.x branch and rebase at that time.

**Comment by adrianreber** [comment]
Verified on the 3.x branch.

**Pull request merged**
