### PR TITLE
Update openmpi to 4.1.4

### PR DESCRIPTION
**Pull request by whophil**
Addresses #1404 

FYI @ruixingw

### CODE REVIEW

**Comment by adrianreber** [comment]
Thanks for the PR. Please add a signed-off-by to your commit message to make the dco bot happy.

Not sure why the aarch64 CI failed. That setup is completely new and I need to take a closer look why it failed.

**Comment by whophil** [comment]
Updated with signoff. aarch64 build still failing @adrianreber

**Comment by martin-g** [comment]
The error on aarch64 is that `make` is not installed:
```
...
+ make -j32
/var/tmp/rpm-tmp.r6t36l: line 66: make: command not found
error: Bad exit status from /var/tmp/rpm-tmp.r6t36l (%build)
    Bad exit status from /var/tmp/rpm-tmp.r6t36l (%build)
')
```

**Comment by adrianreber** [comment]
> The error on aarch64 is that `make` is not installed:
> ```
> ...
> + make -j32
> /var/tmp/rpm-tmp.r6t36l: line 66: make: command not found
> error: Bad exit status from /var/tmp/rpm-tmp.r6t36l (%build)
>     Bad exit status from /var/tmp/rpm-tmp.r6t36l (%build)
> ')
> ```
> 

Thanks for having a look at it. The error messages are unfortunately hard to read.

BuildRequires: make

Should be the fix. Amending the commit should be good to get this merged.

**Comment by adrianreber** [comment]
@whophil Something is broken with out CI setup. Can you try to rebase? `git pull --rebase` and also squash the commits. I prefer to not have fixup commits in a pull request if possible.

**Comment by martin-g** [comment]
Apologies if this is already known or off-topic here!

At https://github.com/openhpc/ohpc/settings, section `Pull Requests` you can enable `Always suggest updating pull request branches` and `Allow squash merging`.
The first will add a new button in the PR UI to update it to latest `master`.
The second will make it possible for the person who merges the PR to squash and edit the commit message before the merge.

**Comment by whophil** [comment]
@adrianreber squashed and pushed!

**Comment by adrianreber** [comment]
All checks finally finished successfully. Thanks.

**Pull request merged**
