### PR TITLE
Fixes #1619 - Remove mentions of nagios and nrpe

### LINKED ISSUE #1619: Missing `nagios-common-ohpc` (nrpe-ohpc required)
`nagios-common-ohpc` is required by `nagioos-nrpe`, but looks like the package nagios-common-ohpc is already removed by ohpc in source tree? 

https://github.com/openhpc/ohpc/blob/58ce19b408e025f798a8e49a8db6dab2d0ce0870/components/admin/nrpe/SPECS/nrpe.spec#L60

The missing required error:
image

### PR DESCRIPTION
**Pull request by martin-g**

### CODE REVIEW

**Comment by martin-g** [comment]
There are still some more mentions of `nagios` in the recipes:
```
./docs/recipes/install/common/sles_os_repos.tex:15:%%      and Scripting Module}} (*only required for nagios/ganglia)
./docs/recipes/install/common/sles_os_repos.tex:18:%%       {\color{blue}{Server Monitoring Software}} (*only required for nagios/ganglia)
./docs/recipes/install/common/inputs.tex:61:& \texttt{\$\{nagios\_web\_password\}} & {\small \# Nagios web access password} \\
./docs/recipes/install/centos8/x86_64/warewulf/slurm/steps.tex:208:\paragraph{Add \Nagios{} monitoring} \label{sec:add_nagios}
./docs/recipes/install/centos8/x86_64/warewulf/slurm/steps.tex:209:\input{common/nagios}
./docs/recipes/install/centos8/input.local.template:64:enable_nagios="${enable_nagios:-0}"
./docs/recipes/install/centos8/input.local.template:73:nagios_web_password="${nagios_web_password:-unknown}"
./docs/recipes/install/leap15/x86_64/xcat/slurm/steps.tex:222:\paragraph{Add \Nagios{} monitoring} \label{sec:add_nagios}
./docs/recipes/install/leap15/x86_64/xcat/slurm/steps.tex:223:\input{common/nagios}
./docs/recipes/install/leap15/x86_64/warewulf/slurm/steps.tex:216:\paragraph{Add \Nagios{} monitoring} \label{sec:add_nagios}
./docs/recipes/install/leap15/x86_64/warewulf/slurm/steps.tex:217:\input{common/nagios_suse}
./docs/recipes/install/leap15/x86_64/warewulf/openpbs/steps.tex:198:\paragraph{Add \Nagios{} monitoring} \label{sec:add_nagios}
./docs/recipes/install/leap15/x86_64/warewulf/openpbs/steps.tex:199:\input{common/nagios_suse}
./docs/recipes/install/leap15/input.local.template:54:enable_nagios="${enable_nagios:-0}"
./docs/recipes/install/leap15/input.local.template:63:nagios_web_password="${nagios_web_password:-unknown}"
./docs/recipes/install/leap15/aarch64/warewulf/slurm/steps.tex:204:\paragraph{Add \Nagios{} monitoring} \label{sec:add_nagios}
./docs/recipes/install/leap15/aarch64/warewulf/slurm/steps.tex:205:\input{common/nagios_suse}
./docs/recipes/install/leap15/aarch64/warewulf/openpbs/steps.tex:188:\paragraph{Add \Nagios{} monitoring} \label{sec:add_nagios}
./docs/recipes/install/leap15/aarch64/warewulf/openpbs/steps.tex:189:\input{common/nagios_suse}
./docs/recipes/install/rocky8/x86_64/xcat/slurm/steps.tex:221:\paragraph{Add \Nagios{} monitoring} \label{sec:add_nagios}
./docs/recipes/install/rocky8/x86_64/xcat/slurm/steps.tex:222:\input{common/nagios}
./docs/recipes/install/rocky8/x86_64/xcat_stateful/slurm/steps.tex:266:\paragraph{Add \Nagios{} monitoring} \label{sec:add_nagios}
./docs/recipes/install/rocky8/x86_64/xcat_stateful/slurm/steps.tex:267:\input{common/nagios_stateful}
./docs/recipes/install/rocky8/x86_64/warewulf/slurm/steps.tex:213:\paragraph{Add \Nagios{} monitoring} \label{sec:add_nagios}
./docs/recipes/install/rocky8/x86_64/warewulf/slurm/steps.tex:214:\input{common/nagios}
./docs/recipes/install/rocky8/x86_64/warewulf/openpbs/steps.tex:189:\paragraph{Add \Nagios{} monitoring} \label{sec:add_nagios}
./docs/recipes/install/rocky8/x86_64/warewulf/openpbs/steps.tex:190:\input{common/nagios}
./docs/recipes/install/rocky8/input.local.template:64:enable_nagios="${enable_nagios:-0}"
./docs/recipes/install/rocky8/input.local.template:73:nagios_web_password="${nagios_web_password:-unknown}"
./docs/recipes/install/rocky8/aarch64/warewulf/slurm/steps.tex:195:\paragraph{Add \Nagios{} monitoring} \label{sec:add_nagios}
./docs/recipes/install/rocky8/aarch64/warewulf/slurm/steps.tex:196:\input{common/nagios}
./docs/recipes/install/rocky8/aarch64/warewulf/openpbs/steps.tex:176:\paragraph{Add \Nagios{} monitoring} \label{sec:add_nagios}
./docs/recipes/install/rocky8/aarch64/warewulf/openpbs/steps.tex:177:\input{common/nagios}
```

**Comment by adrianreber** [comment]
Does the documentation still build if you remove `.tex` files?

I am in favour of removing unused packages from the 3.x branch, but I thin we can leave the `tex` files for now.

**Comment by martin-g** [comment]
I don't have experience with .tex file format. 
And I don't know how to build the docs (never bothered to check).

**Comment by adrianreber** [comment]
If you remove the changes in `misc/` and `docs/` for now this looks mergeable.

**Comment by martin-g** [comment]
> If you remove the changes in `misc/` and `docs/` for now this looks mergeable.

Done!

**Comment by markjens** [comment]
Hi! 
What is the reason to keep the docs for Nagios still around ?
I was following the docs for Rocky and when I reached the step `Add Nagios monitoring` I faced a problem with missing packages. After some googling I found this PR and understood that Nagios is not supported/recommended for a long time but the docs still mention it.

**Comment by adrianreber** [comment]
We are removing the nagios docs from the upcoming 3.0 release. The 2.x branch probably still has it mentioned even if the packages do not exist. So if we do one more 2.x release we should probably remove it, right.

**Comment by martin-g** [comment]
@adrianreber The docs are still here in 3.x:
- https://github.com/openhpc/ohpc/blob/3.x/docs/recipes/install/common/nagios.tex
- https://github.com/openhpc/ohpc/blob/3.x/docs/recipes/install/rocky9/x86_64/warewulf/slurm/steps.tex#L214

This PR didn't touch the `docs` as requested with https://github.com/openhpc/ohpc/pull/1744#issuecomment-1482414809

**Comment by adrianreber** [comment]
Ah, you are right. Let's remove it from the `steps.tex` files.

@martin-g can you open another PR to remove the nagios chapter from all `steps.tex` files?

**Pull request merged**
