### PR TITLE
Allow for the conditional building of serial versions

### PR DESCRIPTION
**Pull request by opoplawski**
of the netcdf-cxx4 and netcdf-fortran packages

### CODE REVIEW

**Comment by adrianreber** [comment]
The CI errors are my fault. I need to trigger a real built in OBS.

**Comment by adrianreber** [comment]
Deep in the logs of the CI I see there is BuildRequires: make missing for the cxx version.

**Comment by opoplawski** [comment]
Thanks, added.

**Comment by adrianreber** [comment]
Merged via #1891

**Pull request closed without merging**
