### PR TITLE
Add hpc-workspace to OpenHPC

### PR DESCRIPTION
**Pull request by georgiastuart**
This is an attempt to fulfill #1403 

[hpc-workspace](https://github.com/holgerBerger/hpc-workspace) is an admin tool for managing directories with associated expiration dates and share groups. 

This PR adds:
- hpc-workspace spec file
- hpc-workspace license
- hpc-workspace config template

Open questions:
- Is the admin category the correct spot for this component?
- I included the default daily cleanup script, should that be changed?

### CODE REVIEW

**Comment by adrianreber** [comment]
I approved the CI jobs.

In the case of adding something new please do not include fixup commits in the PR. In this case squashing the commits would be the right thing to do.

Also please now merge commits. Please try to rebase your branch.

**Comment by adrianreber** [comment]
Oh, and please add a signed-off-by to make our do not happy.

**Comment by georgiastuart** [comment]
I'm going to close this and try again, I messed up the sign off redo

**Comment by adrianreber** [comment]
> I'm going to close this and try again, I messed up the sign off redo
> 

Usually it is not necessary to close a PR. You can just force push. But in the end you just do whatever works best for you.

**Pull request closed without merging**
