### PR TITLE
runtimes/charliecloud: add a "BuildRequires: make"

### PR DESCRIPTION
**Pull request by martin-g**
Add a test mapping too

Successful OBS builds:
* https://obs.openhpc.community/package/live_build_log/home:mgrigorov/charliecloud-gnu12-openmpi4/OpenHPC_3.0_Factory_openEuler_22.03/x86_64
* https://obs.openhpc.community/package/live_build_log/home:mgrigorov/charliecloud-gnu12-openmpi4/OpenHPC_3.0_Factory_openEuler_22.03/aarch64

### CODE REVIEW

**Comment by martin-g** [comment]
The test fails on Rocky with:
```
$ ch-run alpine -- cat /etc/os-release
ch-run[13]: error: can't init user+mount namespaces: Operation not permitted (ch_core.c:400 1)
```

Google suggests https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux_atomic_host/7/html-single/getting_started_with_containers/index#user_namespaces_options but I cannot find how to pass kernel args (`namespace.unpriv_enable=1`) and I cannot pass ` user.max_user_namespaces=15076` neither as `docker run --sysctl ...` (see https://docs.docker.com/engine/reference/commandline/run/#sysctl) nor with `sysctl -w  user.max_user_namespaces=15076` inside the container (because of: `read-only file system`)

Ideas ?

**Comment by adrianreber** [comment]
I think your analysis is not correct. User namespaces where not enabled in RHEL 7 and clones. We are running, however, not on a  RHEL 7 kernel. This is a Ubuntu kernel.

My first try would be to see if running a privileged container enables us to use user namespaces in the containers set up by GitHub Actions.

**Comment by martin-g** [comment]
I've tried the following on my dev machine (Ubuntu 22.04 x86_64):
```
$ docker run -it --rm --privileged  rocky-full:8 bash
[root@4b3237235bad /]# USER=root ch-run alpine -- cat /etc/os-release
ch-run[13]: error: Invalid argument (ch_core.c:226 22)
```

rocky-full is rockylinux:8 with singularity-ce and charliecloud installed, and `singularity build --sandbox alpine docker://alpine:3` already done

**Comment by martin-g** [comment]
Same without privileged:
```
$ docker run -it --rm  rocky-full:8 bash
[root@16ddd10c2dc6 /]# USER=root ch-run alpine -- cat /etc/os-release
ch-run[13]: error: can't init user+mount namespaces: Operation not permitted (ch_core.c:400 1)
```

**Comment by adrianreber** [comment]
So running a container inside of a container is described for example in this article: https://www.redhat.com/sysadmin/podman-inside-container

Using podman I can run the charliecloud test locally inside of a container.

Your error messages are different if running with and without `--privileged`.

**Comment by martin-g** [comment]
> Your error messages are different if running with and without `--privileged`.

Yes. This is what I expect to see at GHA with 9d6977c66 too.

**Comment by martin-g** [comment]
Nice! RockyLinux passed!
I'll see how to exclude charliecloud for openEuler because it does not provide singularity/apptainer at the moment.

**Comment by martin-g** [comment]
All checks passed!
I think we can simplify the `[JOB_]SKIP_CI_SPECS` env vars. IMO there is no need of two vars. A job could just append specs to the global one.
Let me try it!

**Comment by martin-g** [comment]
The PR is ready for review!

**Pull request merged**
