### PR TITLE
3.x ChangeLog update for openEuler support

### PR DESCRIPTION
**Pull request by Yikun**
Append the release note as discussion [1].

[1] https://github.com/openhpc/ohpc/pull/1867#discussion_r1322930546

Signed-off-by: Yikun Jiang <yikunkero@gmail.com>

### CODE REVIEW

**Comment by Yikun** [comment]
cc @martin-g @mghpcsim @adrianreber

**Review by martin-g — APPROVED** [review]
It seems #1867 has been merged without applying the suggestions: https://github.com/openhpc/ohpc/pull/1867#discussion_r1322930546

**Comment by adrianreber** [comment]
@martin-g does this PR include all your suggestions from #1867?

**Comment by martin-g** [comment]
> @martin-g does this PR include all your suggestions from https://github.com/openhpc/ohpc/pull/1867?

Yes!
We decided to not add an entry in the known issues section. 
Apparently `SP`s work differently in openEuler and this is documented in its docs.

**Comment by adrianreber** [comment]
SP?

**Comment by martin-g** [comment]
Service Pack, e.g. `22.03 LTS SP2` 

This PR says that only `22.03 LTS` is supported. We think this should be enough for the OpenHPC 3.x changelog

**Comment by adrianreber** [comment]
Ah, right. Makes sense.

**Comment by ohpcsim** [comment]
Thanks for adding the stuff I left off from the previous PR; rebased and merged

**Pull request merged**
