### PR TITLE
Allow for the conditional building of serial versions fo the netcdf p…

### PR DESCRIPTION
**Pull request by opoplawski**
…ackages

This replaces #1752 as requested with conditional versions.

I'm also going to try to work up a version with some additional macros...

### CODE REVIEW

**Comment by adrianreber** [comment]
Thanks. This looks almost ready to be merged from my point of view. Unfortunately our CI scripts cannot handle dependencies correctly. Could you make two PRs out of this. This one just for netcdf and a second for netcdf-cxx and netcdf-fortran. This way CI results should be green.

**Comment by opoplawski** [comment]
okay, this PR has been just reduced to the netcdf package.

**Comment by adrianreber** [comment]
I need to update the CI scripts before merging this. Currently not the correct version is built.

**Comment by adrianreber** [comment]
Please rebase. The test script should now be ready to handle this case correctly.

**Comment by opoplawski** [comment]
Rebased.

**Comment by adrianreber** [comment]
The test system didn't fail but there is following error:
```
 file /opt/ohpc/pub/libs/gnu12/openmpi4/netcdf/4.9.0/bin/nc-config conflicts between attempted installs of netcdf-gnu12-openmpi4-ohpc-4.9.0-19999.ci.ohpc.x86_64 and netcdf-gnu12-ohpc-4.9.0-19999.ci.ohpc.x86_64
```
It seems like there is some collision with parallel install-ability. It could also be that my build script messed something up.

For the next 24 hours the RPMs from CI are available here: https://github.com/openhpc/ohpc/actions/runs/5291658769

**Comment by opoplawski** [comment]
No, I missed changing install_path.  Another go...

**Comment by adrianreber** [comment]
Looks good. Thanks. Locally I have a version of the test suite that can now run the tests using the MPI and the non MPI version of netcdf. Once your fortran and cxx packages are merged I will update the test framework.

**Comment by opoplawski** [comment]
Great, I've now filed #1840 for the cxx4 and fortran packages.

**Pull request merged**
