### PR TITLE
Update Warewulf3-common to v3.10.0

### PR DESCRIPTION
**Pull request by martin-g**
https://github.com/warewulf/warewulf3/commit/c6de604fc76eabfaef2cb99f4c6ae5ed44eff1e0

Add "BuildRequires: make"

Successful build on OBS: https://obs.openhpc.community/package/show/home:mgrigorov/warewulf-common-gnu12-openmpi4

### CODE REVIEW

**Comment by martin-g** [comment]
Only CentOS Stream 9 fails with:
```
2023-02-22T12:47:45.6638327Z error: File must begin with "/": %{perl_vendorlib}/*
```

**Comment by martin-g** [comment]
I also tried to build warewulf-vnfs but it fails because it cannot decide whether to use `mysql` or `mysql5` as a transitive dependency of warewulf-common-ohpc.
I have the feeling/hope that it will auto-resolve itself once this PR is merged and the newer `warewulf-common-ohpc`  is available in the OpenHPC:3.0 repo.

https://obs.openhpc.community/package/show/home:mgrigorov/warewulf-vnfs-gnu12-openmpi4

**Comment by adrianreber** [comment]
Do you have any specific reasons to update it to 3.10.0? I see no problem with it, I am mainly curious if that has something that is important.

**Comment by martin-g** [comment]
@Yikun knows better but it is related to old/broken version of `busybox` in 3.9.0 that causes problems in openEuler.

**Comment by adrianreber** [comment]
Right, now I remember. Makes sense.

**Comment by Yikun** [comment]
It's related to https://github.com/warewulf/warewulf3/issues/315:
- openEuler 22.03 are using Glibc 2.34 (stime() has been deprecated in glibc 2.31)
- Busybox fix the stime bug since busybox v1.32.0 (https://github.com/mirror/busybox/commit/d3539be8f27b8cbfdfee460fe08299158f08bcd9).
- warewulf 3.9.0 are using busybox-1.26.2 (https://github.com/warewulf/warewulf3/issues/315#issuecomment-1328411030)
- warewulf 3.10.0 are using busybox-1.33.1 (https://github.com/warewulf/warewulf3/commit/c74b5151863ab331dc5525409084de61658a5855)

So the stime compiler error should be solved by upgrading warewulf to v3.10.0.

**Comment by adrianreber** [comment]
> Only CentOS Stream 9 fails with:
> 
> ```
> 2023-02-22T12:47:45.6638327Z error: File must begin with "/": %{perl_vendorlib}/*
> ```

Can you try to build require `perl-generators`?

**Comment by martin-g** [comment]
> Can you try to build require `perl-generators`?

Thanks! It helped!

**Pull request merged**
