### PR TITLE
ci: also build and test with the Intel compiler

### PR DESCRIPTION
**Pull request by adrianreber**

### CODE REVIEW

**Comment by adrianreber** [comment]
For now just as a test.

**Comment by adrianreber** [comment]
This fails because there is not enough disk space on the GitHub runners.

**Comment by martin-g** [comment]
openEuler and Leap fail due to:
```
No provider of 'mpich-.github/workflows/test-analysis.yml-ohpc' found.
No provider of 'openmpi4-.github/workflows/test-analysis.yml-ohpc' found.
```

**Comment by martin-g** [comment]
now the problem is that the test jobs need `man` to be installed

**Comment by adrianreber** [comment]
Now the Intel signing key seems broken.

**Pull request merged**
