### PR TITLE
Change ohpc to %{PROJ_NAME} in ohpc-filesystem.spec

### PR DESCRIPTION
**Pull request by Yikun**
Signed-off-by: Yikun Jiang <yikunkero@gmail.com>

### CODE REVIEW

**Comment by Yikun** [comment]
```
Fedora 37 - x[8](https://github.com/openhpc/ohpc/actions/runs/3512998051/jobs/5885315874#step:3:9)6_64                              1.[9](https://github.com/openhpc/ohpc/actions/runs/3512998051/jobs/5885315874#step:3:10) MB/s |  64 MB     00:33    
Fedora 37 openh264 (From Cisco) - x86_64        4.9 kB/s | 2.5 kB     00:00    
Fedora Modular 37 - x86_64                      6.2 kB/s | 3.3 kB     00:00    
Errors during downloading metadata for repository 'fedora-modular':
  - Status code: 503 for https://mirrors.fedoraproject.org/metalink?repo=fedora-modular-37&arch=x86_64 (IP: 152.19.134.142)
Error: Failed to download metadata for repo 'fedora-modular': Cannot prepare internal mirrorlist: Status code: 503 for https://mirrors.fedoraproject.org/metalink?repo=fedora-modular-37&arch=x86_64 (IP: 152.19.[13](https://github.com/openhpc/ohpc/actions/runs/3512998051/jobs/5885315874#step:3:14)4.142)
Error: Process completed with exit code 1.
```

Looks like it flaky error, I think re-trigger will help. It was passed in my fork repo:
https://github.com/Yikun/ohpc/actions/runs/3512998031/jobs/5885315634

**Comment by Yikun** [comment]
cc @adrianreber

**Comment by adrianreber** [comment]
Not using `%{PROJ_NAME}` here is by design. We want all packages to be usable outside of the OpenHPC project, but the ohpc-filesystem package is specific to OpenHPC and therefore the value is hard coded here. At least that is the reason I remember. I am leaning towards not merging this PR.

**Comment by Yikun** [comment]
@adrianreber OK, thanks for the info

**Pull request closed without merging**
