### PR TITLE
2.0

### PR DESCRIPTION
**Pull request by srinathv**
*replacement of RPM_OPT_FLAG with "-O3 -fsimdmath" and -llapack,-lblas with "-armpl"
* added -fPIC for scotch also
* scotch-arm1 and scalapack-arm1-mpich  both OS build in OBS.

### CODE REVIEW

**Comment by koomie** [comment]
@srinathv, you will need to "sign" your commits in order to accept the DCO (https://github.com/openhpc/ohpc/wiki/Contributions)

**Comment by srinathv** [comment]
I see . that I need to use "git commit -s" on commits to sing off.  How
do I do that to past commits?

Thank you for your time.
===============
Srinath Vadlamani
===============

**Comment by koomie** [comment]
You can amend specific commits or use filter-branch to sign the last `n` commits. See, for example: https://gist.github.com/kwk/d70f20d17b18c4f3296d

**Comment by srinathv** [comment]
I followed :
https://github.com/openhpc/ohpc/pull/1155/checks
but still see sign off issues.
Thank you for your time.
===============
Srinath Vadlamani
===============

**Comment by srinathv** [comment]
It appears there are 4 commits that have a bad email address for Karl.
Thank you for your time.
===============
Srinath Vadlamani
===============

**Comment by koomie** [comment]
I think you have gotten yourself in a pickle with your merges from upstream (and you have now signed commits that were not your changes). You should probably be rebasing your changes on top of the upstream changes for a clean PR.

If it's not too much trouble, I'd suggest branching again from the current 2.0  in your fork and apply your changes for a new PR.

**Pull request closed without merging**
