### PR TITLE
Add MPICH spec file

### PR DESCRIPTION
**Pull request by raffenet**

### CODE REVIEW

**Comment by raffenet** [comment]
I based this largely on the MVAPICH2 spec file. I didn't address all the other parts of the repo that referenced the various MPI families. I can update the request if that is preferred.

**Comment by raffenet** [comment]
Any feedback on this request?

**Comment by koomie** [comment]
Thanks a bunch for this PR @raffenet. I've been holding off temporarily as it is requesting a new addition, and I'm expecting we will be advertising a new component addition request process to the community shortly (hopefully by the end of this week). Assuming that happens, I was going to see if you might be amenable to submitting a request for MPICH and can refer back to this PR that you've contributed a starting .spec file.

**Comment by koomie** [comment]
@raffenet, the submission site for new component requests is now available at:  https://github.com/openhpc/submissions

Would you consider adding MPICH as a new request there? (it should be hopefully be a reasonably quick submission process).

**Comment by raffenet** [comment]
Perfect, will do!

**Comment by koomie** [comment]
Just an FYI, the first round of reviews will be based on submissions received by Monday, September 26th, 2016. (Sorry it's a short turn around time; this is to try and meet a target next release for SC'16).

**Comment by koomie** [comment]
Thanks for doing the submission.

**Comment by raffenet** [comment]
No problem. Should we close this pull request then?

**Comment by koomie** [comment]
I'd say let's leave it open for the time being as it can be a starting point.

**Pull request closed without merging**
