### PR TITLE
ucontext not supportet by newer glibc version

### PR DESCRIPTION
**Pull request by mslacken**
See also 
https://sourceware.org/git/gitweb.cgi?p=glibc.git;a=commitdiff;h=251287734e89a52da3db682a8241eb6bccc050c9;hp=c86ed71d633c22d6f638576f7660c52a5f783d66

### CODE REVIEW

**Comment by adrianreber** [comment]
Looks correct; I had to do similar patches for another project. Is upstream tau still active, had they had a look at your patch?

**Comment by mslacken** [comment]
On Mo, 2017-11-27 at 15:26 +0000, Adrian Reber wrote:
> Looks correct; I had to do similar patches for another project. Is
> upstream tau still active, had they had a look at your patch?
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
Hello Adrian,
the fix will be in the next point release, see the attached mail.

kind regards,
Christian
-- 
Christian Goll
CGoll@suse.de

SUSE Linux GmbH
GF: Felix Imendörffer, Jane Smithard, Graham Norton HRB 21284 (AG
Nürnberg)

**Comment by adrianreber** [comment]
Cool, I am 👍 for merging this.

**Comment by crbaird** [comment]
Thanks for the PR, @mslacken

**Pull request merged**
