### PR TITLE
valgrind：newer RPM requires indexed 'Source'

### PR DESCRIPTION
**Pull request by huangtianhua**

### CODE REVIEW

**Comment by adrianreber** [comment]
Please add a Signed-off-by and keep the indentation.

**Comment by huangtianhua** [comment]
@adrianreber 
I have added the Signed-off-by, but the DCO still failed :(

**Comment by adrianreber** [comment]
The first commit is not signed-off-by. In this case it probably makes sense to squash the commits into one.

**Comment by huangtianhua** [comment]
I reopened another pr: https://github.com/openhpc/ohpc/pull/1578, but seems still DCO check failed :(

**Comment by martin-g** [comment]
@huangtianhua It fails because of `Expected "huangtianhua [huangtianhua@huawei.com](mailto:huangtianhua@huawei.com)", but got "huangtianhua [tiantian223@163.com](mailto:tiantian223@163.com)".`
See the bottom of https://github.com/openhpc/ohpc/pull/1578/checks?check_run_id=8800825694

**Pull request closed without merging**
