### PR TITLE
hdf5: Update to 1.14.5

### PR DESCRIPTION
**Pull request by martin-g**

### CODE REVIEW

**Comment by martin-g** [comment]
The error in the tests is not very clear to me...

**Comment by adrianreber** [comment]
I was running it locally in a container and I saw:

```
ohpc@0f4ae85d3bac:/share/ohpc/tests/libs/hdf5/test-env-variables-new/C/H5T> ./test.sh
Testing C/H5T/h5ex_t_int...  Passed
Testing C/H5T/h5ex_t_intatt...  Passed
Testing C/H5T/h5ex_t_float...  Passed
Testing C/H5T/h5ex_t_floatatt...  Passed
Testing C/H5T/h5ex_t_enum...  Passed
Testing C/H5T/h5ex_t_enumatt...  Passed
Testing C/H5T/h5ex_t_bit...  Passed
Testing C/H5T/h5ex_t_bitatt...  Passed
Testing C/H5T/h5ex_t_opaque...  Passed
Testing C/H5T/h5ex_t_opaqueatt...  Passed
Testing C/H5T/h5ex_t_array...  Passed
Testing C/H5T/h5ex_t_arrayatt...  Passed
Testing C/H5T/h5ex_t_vlen...  FAILED!
Testing C/H5T/h5ex_t_vlenatt...  FAILED!
Testing C/H5T/h5ex_t_string...  Passed
Testing C/H5T/h5ex_t_stringatt...  Passed
Testing C/H5T/h5ex_t_vlstring...  Passed
Testing C/H5T/h5ex_t_vlstringatt...  Passed
Testing C/H5T/h5ex_t_cmpd...  Passed
Testing C/H5T/h5ex_t_cmpdatt...  Passed
Testing C/H5T/h5ex_t_commit...  Passed
Testing C/H5T/h5ex_t_objref...  Passed
Testing C/H5T/h5ex_t_objrefatt...  Passed
Testing C/H5T/h5ex_t_regref...  Passed
Testing C/H5T/h5ex_t_regrefatt...  Passed
Testing C/H5T/h5ex_t_cpxcmpd...  Passed
Testing C/H5T/h5ex_t_cpxcmpdatt...  Passed
Testing C/H5T/h5ex_t_convert...  Passed
2 tests failed in C/H5T/
```

The test compares the output of the tools with some predefined output. Not sure where the predefined output comes from. Maybe that needs to be updated.

**Comment by martin-g** [comment]
Thanks!
The comparison happens [here](https://github.com/openhpc/ohpc/blob/611b01fe68188bae48768b00300d3b37662b253b/tests/libs/hdf5/test-env-variables-new/C/H5T/test.sh.in#L66) but I cannot figure out where the [echoed](https://github.com/openhpc/ohpc/blob/611b01fe68188bae48768b00300d3b37662b253b/tests/libs/hdf5/test-env-variables-new/C/H5T/test.sh.in#L70) output goes to. It seems it is not written into a `.log` file and that's why we cannot see the diff.

**Comment by martin-g** [comment]
Here is the diff:
```diff
:49:38.9351165Z ================================================
2024-10-17T13:49:38.9351892Z Log file: ./tests/libs/hdf5/test-env-variables-new/C/H5T/h5ex_t_vlen.ddl.diff.log
2024-10-17T13:49:38.9352645Z --- tmp.test	2024-10-17 13:49:22.049008370 +0000
2024-10-17T13:49:38.9353225Z +++ ./testfiles/114/h5ex_t_vlen.ddl	2024-10-17 13:47:41.836252996 +0000
2024-10-17T13:49:38.9353818Z @@ -1,7 +1,7 @@
2024-10-17T13:49:38.9354154Z  HDF5 "h5ex_t_vlen.h5" {
2024-10-17T13:49:38.9354464Z  GROUP "/" {
2024-10-17T13:49:38.9354835Z     DATASET "DS1" {
2024-10-17T13:49:38.9355252Z -      DATATYPE  H5T_VLEN { H5T_STD_I32LE }
2024-10-17T13:49:38.9355662Z +      DATATYPE  H5T_VLEN { H5T_STD_I32LE}
2024-10-17T13:49:38.9356182Z        DATASPACE  SIMPLE { ( 2 ) / ( 2 ) }
2024-10-17T13:49:38.9356584Z        DATA {
2024-10-17T13:49:38.9356932Z        (0): (3, 2, 1), (1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, 144)
2024-10-17T13:49:38.9357491Z ================================================
2024-10-17T13:49:38.9358232Z Log file: ./tests/libs/hdf5/test-env-variables-new/C/H5T/h5ex_t_vlenatt.ddl.diff.log
2024-10-17T13:49:38.9358882Z --- tmp.test	2024-10-17 13:49:22.065008477 +0000
2024-10-17T13:49:38.9359570Z +++ ./testfiles/114/h5ex_t_vlenatt.ddl	2024-10-17 13:47:41.836252996 +0000
2024-10-17T13:49:38.9360248Z @@ -6,7 +6,7 @@
2024-10-17T13:49:38.9360531Z        DATA {
2024-10-17T13:49:38.9360920Z        }
2024-10-17T13:49:38.9361220Z        ATTRIBUTE "A1" {
2024-10-17T13:49:38.9361635Z -         DATATYPE  H5T_VLEN { H5T_STD_I32LE }
2024-10-17T13:49:38.9362153Z +         DATATYPE  H5T_VLEN { H5T_STD_I32LE}
2024-10-17T13:49:38.9362603Z           DATASPACE  SIMPLE { ( 2 ) / ( 2 ) }
2024-10-17T13:49:38.9362996Z           DATA {
2024-10-17T13:49:38.9363438Z           (0): (3, 2, 1), (1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, 144)
```

**Comment by martin-g** [comment]
@adrianreber Please review!

**Pull request merged**
