### PR TITLE
Change Source to Source0 in warewulf.spec

### PR DESCRIPTION
**Pull request by Yikun**
Signed-off-by: Yikun Jiang <yikunkero@gmail.com>

### CODE REVIEW

**Comment by Yikun** [comment]
cc @adrianreber

**Comment by adrianreber** [comment]
Not sure why CI cannot handle this PR correctly. Can you do a `git pull --rebase` and ` git push ... --force`

**Comment by Yikun** [comment]
hmm, it's a little bit weired

**Comment by adrianreber** [comment]
Ah, you were able to fix it. Very good.

**Comment by Yikun** [comment]
Emm, just FYI, I found that I have to sync my fork repo (2.x) to upstream 2.x then the CI passed.

**Comment by adrianreber** [comment]
> Emm, just FYI, I found that I have to sync my fork repo (2.x) to upstream 2.x then the CI passed.

Good.

**Pull request merged**
