### PR TITLE
Use the proper path for the nologin shell

### LINKED ISSUE #1017: fix slurm rpm spec typo
ref :  https://github.com/openhpc/ohpc/blob/v1.3.8.GA/components/rms/slurm/SPECS/slurm.spec#L710
```
  -d %{_sysconfdir} -g slurm -s /bin/nologin -r slurm -u 202
````

I think should be `/sbin/nologin`, not `/bin/nologin`

### PR DESCRIPTION
**Pull request by amblakem**
Should fix #1017.

Signed-off-by: Aaron Blakeman <aaron.blakeman@intel.com>

### CODE REVIEW

**Comment by amblakem** [comment]
Alongside the `slurm.spec` file is a `spec.latest.patch` file which also has this issue[1].  This patch appears to be out of sync as it's referencing SLURM 17.11.5.  I can't find references to where this patch is used, can it be deleted?

[1] https://github.com/openhpc/ohpc/blob/obs/OpenHPC_1.3.8_Factory/components/rms/slurm/SPECS/spec.latest.patch#L533

**Comment by koomie** [comment]
> Alongside the `slurm.spec` file is a `spec.latest.patch` file which also has this issue[1]. This patch appears to be out of sync as it's referencing SLURM 17.11.5. I can't find references to where this patch is used, can it be deleted?
> 
> [1] https://github.com/openhpc/ohpc/blob/obs/OpenHPC_1.3.8_Factory/components/rms/slurm/SPECS/spec.latest.patch#L533

This patch isn't used formally in the build process, but helps us keep track of changes we have to apply against the upstream .spec file. I've updated it to reflect changes against v18.08.8 and I've landed your 6ed9982 patch on the ohpc 1.3.8.1 branch.

**Comment by amblakem** [comment]
Gotcha, that makes sense.  This is good information, thank you for explaining @koomie.

**Comment by koomie** [comment]
This was landed in 7d240cd9a85be06271ca43d10488faaf1101d222 for v1.3.8.1 and carried forward.

**Pull request closed without merging**
