### PR TITLE
warewulf: copy config.sub too

### PR DESCRIPTION
**Pull request by pawosm-arm**
Signed-off-by: Paul Osmialowski <pawel.osmialowski@arm.com>

### CODE REVIEW

**Comment by jmstover** [comment]
I actually don't see an issue in it. @pawosm-arm , what was the reasoning behind copying the config.guess to the build directory? It... shouldn't need it, but if there's some valid reason I can add it upstream so it's there.

**Comment by pawosm-arm** [comment]
This is possible fix to address build failure on SuSe/AArch64, from the log you can find that config.sub as shipped with warewulf don't quite understand what -suse- means.

**Comment by jmstover** [comment]
Ahh... Yeah, we don't move out much beyond the RHEL based world. ;)

On an SL 6.5 provisioner I have here, the autoconf and RPM config.guess are the same, so there wouldn't be an issue that I can foresee also adding this in upstream as well so the patch isn't needed constantly.

**Comment by pawosm-arm** [comment]
Actually this patch helps with building on SuSe:
https://build.openhpc.community/package/show/home:eric:OpenHPC:1.2:Factory/warewulf-ipmi

**Pull request merged**
