### PR TITLE
lmod: Update to 8.7.49

### PR DESCRIPTION
**Pull request by martin-g**

### CODE REVIEW

**Comment by martin-g** [comment]
https://github.com/openhpc/ohpc/actions/runs/11138923266/job/30954689982?pr=2035
Is Lmod broken in the new version ?!

**Comment by martin-g** [comment]
I think this is the problem we face too - https://github.com/TACC/Lmod/issues/718#issuecomment-2343334206

**Comment by adrianreber** [comment]
There have been a couple of lmod releases since your revert. Do you think we should try upgrade lmod once more? The git history at lmod is not clear if this is now fixed or not.

**Comment by martin-g** [comment]
https://github.com/TACC/Lmod/issues/718 is still opened, but there are several commits to https://github.com/TACC/Lmod/commits/main/init/bash.in
Let's try !

**Pull request merged**
