### PR TITLE
Fix slurm.conf NodeName config bug

### PR DESCRIPTION
**Pull request by xiexianbin**
issue #1335

Signed-off-by: xiexianbin <me@xiexianbin.cn>

### CODE REVIEW

**Comment by adrianreber** [comment]
Can you please rebase this PR?

**Comment by xiexianbin** [comment]
rebase Done

**Comment by adrianreber** [comment]
This sounds correct from my point of view, but I am not 100% sure. @koomie if you have a chance please have a look if this is correct.

**Comment by adrianreber** [comment]
@koomie Please take a look.

**Pull request closed without merging**
