### PR TITLE
ci: use Cirrus CI for aarch64 tests

### PR DESCRIPTION
**Pull request by adrianreber**
Drone CI does no longer accept new accounts. Run aarch64 tests on Cirrus CI.

@utdsimmons This tries to run aarch64 based CI on Cirrus.

### CODE REVIEW

**Comment by adrianreber** [comment]
@utdsimmons See https://cirrus-ci.com/task/6239533627867136 for the result of an aarch64 build.

**Comment by adrianreber** [comment]
The aarch64 builder says:
```
Wrote: /home/ohpc/rpmbuild/RPMS/aarch64/plasma-gnu9-ohpc-21.8.29-1.ohpc.2.0.0.aarch64.rpm
```
Looks like it works.

**Comment by ohpcsim** [comment]
CI run was successful after adding cirrus ci as an authorized app; rebasing and merging

**Comment by utdsimmons** [comment]
adding cirrus ci support for aarch64 builds

**Pull request merged**
