### PR TITLE
Boost update for PSXE 2020

### PR DESCRIPTION
**Pull request by jcsiadal**
Signed-off-by: jcsiadal <jeremy.c.siadal@intel.com>

This updates boost to build with Intel nextgen switch. Unfortunately, ICC then switches to a clang backend, but b2 continues to use old ICC switches. Options like xCORE cause the nextgen ICC to crash.

I did a rather hacky update using sed to fix up a bunch of files. This should be more cleanly migrated to a patchfile (and merged with the current Intel patch). In the event I can't work on this over the next few weeks, I wanted to get the changes uploaded.

The reason for so many "-O3" replacements is that it's a fast and safe method to replace a switch I need to remove. I would clean these up after I can review the patched files.

Other updates:
Depending on what backend compiler is needed, Intel MPI uses different wrappers. Instead of confining this to boost, I added new macros to OHPC_macros. There's a table of the correct wrapper in our docs. Also should note that some other OpenHPC components could be using the wrong wrapper.

Made patch names consistent with each other. I don't see a need for the version in the name, since a patch either applies to the current package version or it should be deleted.

### CODE REVIEW

**Comment by jcsiadal** [comment]
Per last TSC, @koomie will loop back on whether to implement the nextgen switch, or if the issue has been resolved in the next boost release. Putting this on hold for now.

If we do need to fix this, I'll own getting a proper patchfile implemented.

**Comment by koomie** [comment]
I ended up creating a standalone patch for the bjam files that you were changing with sed.  This allowed the intel compiler variant builds to complete. Not all of the tests are passing in CI though with some undefined references when compiling some example programs against the installed boost built with nextgen option. The version of boost we're building for ohpc 2.0 all passes for gcc9, so this may be an issue mixing oldgen/nextgen intel libs.

I'll try to grab a snapshot when this configuration rolls around again in CI.

Separate comment on the wrapper business. We set things up with the compatibility package for impi such that `mpicc` maps to `mpiicc` when the intel variant is loaded. This is intentional to make things easier for the end user as most just assume mpicc is what they want.

**Comment by koomie** [comment]
Unfortunately, this issue turns out to be what I was most worried about. Most of our Boost tests work I suspect because a lot of Boost is header only. However, when you need to link against a lib that was  compiled with `-qnextgen` and you are not using that flag for the current compilation, you can get unresolved C++ symbols. Here is an example that we see with an ohpc test trying to link against Boost's regex library

#### compile example code that ships with boost 1.71.0 with `-qnextgen` option.  Works fine.

```
karl@sms001 test (2.0) $ icpc -qnextgen -I/opt/ohpc/pub/libs/intel/openmpi4/boost/1.71.0/include -g -O2 -L/opt/ohpc/pub/libs/intel/openmpi4/boost/1.71.0/lib  -lboost_regex named_subexpressions_test.cpp 
karl@sms001 test (2.0) $ ./a.out
karl@sms001 test (2.0) $ echo $?
0
```

#### compile example code that ships with boost 1.71.0 without `-qnextgen` option. It no workie.

```
karl@sms001 test (2.0) $ icpc -I/opt/ohpc/pub/libs/intel/openmpi4/boost/1.71.0/include -g -O2 -L/opt/ohpc/pub/libs/intel/openmpi4/boost/1.71.0/lib  -lboost_regex named_subexpressions_test.cpp 
/tmp/icpcbunIMt.o: In function `boost::basic_regex<wchar_t, boost::regex_traits<wchar_t, boost::cpp_regex_traits<wchar_t> > >::assign(wchar_t const*, wchar_t const*, unsigned int)':
/opt/ohpc/pub/libs/intel/openmpi4/boost/1.71.0/include/boost/regex/v4/basic_regex.hpp:387: undefined reference to `boost::basic_regex<wchar_t, boost::regex_traits<wchar_t, boost::cpp_regex_traits<wchar_t> > >::do_assign(wchar_t const*, wchar_t const*, unsigned int)'
/tmp/icpcbunIMt.o: In function `boost::re_detail_107100::perl_matcher<wchar_t const*, std::allocator<boost::sub_match<wchar_t const*> >, boost::regex_traits<wchar_t, boost::cpp_regex_traits<wchar_t> > >::perl_matcher(wchar_t const*, wchar_t const*, boost::match_results<wchar_t const*, std::allocator<boost::sub_match<wchar_t const*> > >&, boost::basic_regex<wchar_t, boost::regex_traits<wchar_t, boost::cpp_regex_traits<wchar_t> > > const&, boost::regex_constants::_match_flags, wchar_t const*)':
/opt/ohpc/pub/libs/intel/openmpi4/boost/1.71.0/include/boost/regex/v4/perl_matcher.hpp:391: undefined reference to `boost::re_detail_107100::perl_matcher<wchar_t const*, std::allocator<boost::sub_match<wchar_t const*> >, boost::regex_traits<wchar_t, boost::cpp_regex_traits<wchar_t> > >::construct_init(boost::basic_regex<wchar_t, boost::regex_traits<wchar_t, boost::cpp_regex_traits<wchar_t> > > const&, boost::regex_constants::_match_flags)'
/tmp/icpcbunIMt.o: In function `boost::basic_regex<char, boost::regex_traits<char, boost::cpp_regex_traits<char> > >::assign(char const*, char const*, unsigned int)':
/opt/ohpc/pub/libs/intel/openmpi4/boost/1.71.0/include/boost/regex/v4/basic_regex.hpp:387: undefined reference to `boost::basic_regex<char, boost::regex_traits<char, boost::cpp_regex_traits<char> > >::do_assign(char const*, char const*, unsigned int)'
/tmp/icpcbunIMt.o: In function `boost::re_detail_107100::perl_matcher<char const*, std::allocator<boost::sub_match<char const*> >, boost::regex_traits<char, boost::cpp_regex_traits<char> > >::perl_matcher(char const*, char const*, boost::match_results<char const*, std::allocator<boost::sub_match<char const*> > >&, boost::basic_regex<char, boost::regex_traits<char, boost::cpp_regex_traits<char> > > const&, boost::regex_constants::_match_flags, char const*)':
/opt/ohpc/pub/libs/intel/openmpi4/boost/1.71.0/include/boost/regex/v4/perl_matcher.hpp:391: undefined reference to `boost::re_detail_107100::perl_matcher<char const*, std::allocator<boost::sub_match<char const*> >, boost::regex_traits<char, boost::cpp_regex_traits<char> > >::construct_init(boost::basic_regex<char, boost::regex_traits<char, boost::cpp_regex_traits<char> > > const&, boost::regex_constants::_match_flags)'
/tmp/icpcbunIMt.o: In function `boost::re_detail_107100::perl_matcher<char const*, std::allocator<boost::sub_match<char const*> >, boost::regex_traits<char, boost::cpp_regex_traits<char> > >::match_prefix()':
/opt/ohpc/pub/libs/intel/openmpi4/boost/1.71.0/include/boost/regex/v4/perl_matcher_common.hpp:346: undefined reference to `boost::match_results<char const*, std::allocator<boost::sub_match<char const*> > >::maybe_assign(boost::match_results<char const*, std::allocator<boost::sub_match<char const*> > > const&)'
/tmp/icpcbunIMt.o: In function `boost::re_detail_107100::perl_matcher<char const*, std::allocator<boost::sub_match<char const*> >, boost::regex_traits<char, boost::cpp_regex_traits<char> > >::match_match()':
/opt/ohpc/pub/libs/intel/openmpi4/boost/1.71.0/include/boost/regex/v4/perl_matcher_non_recursive.hpp:1108: undefined reference to `boost::match_results<char const*, std::allocator<boost::sub_match<char const*> > >::maybe_assign(boost::match_results<char const*, std::allocator<boost::sub_match<char const*> > > const&)'
/tmp/icpcbunIMt.o: In function `boost::cpp_regex_traits<char>::transform[abi:cxx11](char const*, char const*) const':
/opt/ohpc/pub/libs/intel/openmpi4/boost/1.71.0/include/boost/regex/v4/cpp_regex_traits.hpp:962: undefined reference to `boost::re_detail_107100::cpp_regex_traits_implementation<char>::transform[abi:cxx11](char const*, char const*) const'
/tmp/icpcbunIMt.o: In function `boost::cpp_regex_traits<char>::transform_primary[abi:cxx11](char const*, char const*) const':
/opt/ohpc/pub/libs/intel/openmpi4/boost/1.71.0/include/boost/regex/v4/cpp_regex_traits.hpp:966: undefined reference to `boost::re_detail_107100::cpp_regex_traits_implementation<char>::transform_primary[abi:cxx11](char const*, char const*) const'
/tmp/icpcbunIMt.o: In function `boost::cpp_regex_traits<char>::transform[abi:cxx11](char const*, char const*) const':
/opt/ohpc/pub/libs/intel/openmpi4/boost/1.71.0/include/boost/regex/v4/cpp_regex_traits.hpp:962: undefined reference to `boost::re_detail_107100::cpp_regex_traits_implementation<char>::transform[abi:cxx11](char const*, char const*) const'
/tmp/icpcbunIMt.o: In function `boost::cpp_regex_traits<char>::transform_primary[abi:cxx11](char const*, char const*) const':
/opt/ohpc/pub/libs/intel/openmpi4/boost/1.71.0/include/boost/regex/v4/cpp_regex_traits.hpp:966: undefined reference to `boost::re_detail_107100::cpp_regex_traits_implementation<char>::transform_primary[abi:cxx11](char const*, char const*) const'
/tmp/icpcbunIMt.o: In function `boost::re_detail_107100::perl_matcher<char const*, std::allocator<boost::sub_match<char const*> >, boost::regex_traits<char, boost::cpp_regex_traits<char> > >::match_prefix()':
/opt/ohpc/pub/libs/intel/openmpi4/boost/1.71.0/include/boost/regex/v4/perl_matcher_common.hpp:346: undefined reference to `boost::match_results<char const*, std::allocator<boost::sub_match<char const*> > >::maybe_assign(boost::match_results<char const*, std::allocator<boost::sub_match<char const*> > > const&)'
/opt/ohpc/pub/libs/intel/openmpi4/boost/1.71.0/include/boost/regex/v4/perl_matcher_common.hpp:346: undefined reference to `boost::match_results<char const*, std::allocator<boost::sub_match<char const*> > >::maybe_assign(boost::match_results<char const*, std::allocator<boost::sub_match<char const*> > > const&)'
/opt/ohpc/pub/libs/intel/openmpi4/boost/1.71.0/include/boost/regex/v4/perl_matcher_common.hpp:346: undefined reference to `boost::match_results<char const*, std::allocator<boost::sub_match<char const*> > >::maybe_assign(boost::match_results<char const*, std::allocator<boost::sub_match<char const*> > > const&)'
/opt/ohpc/pub/libs/intel/openmpi4/boost/1.71.0/include/boost/regex/v4/perl_matcher_common.hpp:346: undefined reference to `boost::match_results<char const*, std::allocator<boost::sub_match<char const*> > >::maybe_assign(boost::match_results<char const*, std::allocator<boost::sub_match<char const*> > > const&)'
/opt/ohpc/pub/libs/intel/openmpi4/boost/1.71.0/include/boost/regex/v4/perl_matcher_common.hpp:346: undefined reference to `boost::match_results<char const*, std::allocator<boost::sub_match<char const*> > >::maybe_assign(boost::match_results<char const*, std::allocator<boost::sub_match<char const*> > > const&)'
/tmp/icpcbunIMt.o:/opt/ohpc/pub/libs/intel/openmpi4/boost/1.71.0/include/boost/regex/v4/perl_matcher_common.hpp:346: more undefined references to `boost::match_results<char const*, std::allocator<boost::sub_match<char const*> > >::maybe_assign(boost::match_results<char const*, std::allocator<boost::sub_match<char const*> > > const&)' follow
/tmp/icpcbunIMt.o: In function `boost::cpp_regex_traits<char>::transform[abi:cxx11](char const*, char const*) const':
/opt/ohpc/pub/libs/intel/openmpi4/boost/1.71.0/include/boost/regex/v4/cpp_regex_traits.hpp:962: undefined reference to `boost::re_detail_107100::cpp_regex_traits_implementation<char>::transform[abi:cxx11](char const*, char const*) const'
/tmp/icpcbunIMt.o: In function `boost::cpp_regex_traits<char>::transform_primary[abi:cxx11](char const*, char const*) const':
/opt/ohpc/pub/libs/intel/openmpi4/boost/1.71.0/include/boost/regex/v4/cpp_regex_traits.hpp:966: undefined reference to `boost::re_detail_107100::cpp_regex_traits_implementation<char>::transform_primary[abi:cxx11](char const*, char const*) const'
/tmp/icpcbunIMt.o: In function `boost::re_detail_107100::perl_matcher<wchar_t const*, std::allocator<boost::sub_match<wchar_t const*> >, boost::regex_traits<wchar_t, boost::cpp_regex_traits<wchar_t> > >::match_prefix()':
/opt/ohpc/pub/libs/intel/openmpi4/boost/1.71.0/include/boost/regex/v4/perl_matcher_common.hpp:346: undefined reference to `boost::match_results<wchar_t const*, std::allocator<boost::sub_match<wchar_t const*> > >::maybe_assign(boost::match_results<wchar_t const*, std::allocator<boost::sub_match<wchar_t const*> > > const&)'
/tmp/icpcbunIMt.o: In function `boost::re_detail_107100::perl_matcher<wchar_t const*, std::allocator<boost::sub_match<wchar_t const*> >, boost::regex_traits<wchar_t, boost::cpp_regex_traits<wchar_t> > >::match_match()':
/opt/ohpc/pub/libs/intel/openmpi4/boost/1.71.0/include/boost/regex/v4/perl_matcher_non_recursive.hpp:1108: undefined reference to `boost::match_results<wchar_t const*, std::allocator<boost::sub_match<wchar_t const*> > >::maybe_assign(boost::match_results<wchar_t const*, std::allocator<boost::sub_match<wchar_t const*> > > const&)'
/tmp/icpcbunIMt.o: In function `boost::cpp_regex_traits<wchar_t>::transform[abi:cxx11](wchar_t const*, wchar_t const*) const':
/opt/ohpc/pub/libs/intel/openmpi4/boost/1.71.0/include/boost/regex/v4/cpp_regex_traits.hpp:962: undefined reference to `boost::re_detail_107100::cpp_regex_traits_implementation<wchar_t>::transform[abi:cxx11](wchar_t const*, wchar_t const*) const'
/tmp/icpcbunIMt.o: In function `boost::cpp_regex_traits<wchar_t>::transform_primary[abi:cxx11](wchar_t const*, wchar_t const*) const':
/opt/ohpc/pub/libs/intel/openmpi4/boost/1.71.0/include/boost/regex/v4/cpp_regex_traits.hpp:966: undefined reference to `boost::re_detail_107100::cpp_regex_traits_implementation<wchar_t>::transform_primary[abi:cxx11](wchar_t const*, wchar_t const*) const'
/tmp/icpcbunIMt.o: In function `boost::cpp_regex_traits<wchar_t>::transform[abi:cxx11](wchar_t const*, wchar_t const*) const':
/opt/ohpc/pub/libs/intel/openmpi4/boost/1.71.0/include/boost/regex/v4/cpp_regex_traits.hpp:962: undefined reference to `boost::re_detail_107100::cpp_regex_traits_implementation<wchar_t>::transform[abi:cxx11](wchar_t const*, wchar_t const*) const'
/tmp/icpcbunIMt.o: In function `boost::cpp_regex_traits<wchar_t>::transform_primary[abi:cxx11](wchar_t const*, wchar_t const*) const':
/opt/ohpc/pub/libs/intel/openmpi4/boost/1.71.0/include/boost/regex/v4/cpp_regex_traits.hpp:966: undefined reference to `boost::re_detail_107100::cpp_regex_traits_implementation<wchar_t>::transform_primary[abi:cxx11](wchar_t const*, wchar_t const*) const'
/tmp/icpcbunIMt.o: In function `boost::re_detail_107100::perl_matcher<wchar_t const*, std::allocator<boost::sub_match<wchar_t const*> >, boost::regex_traits<wchar_t, boost::cpp_regex_traits<wchar_t> > >::match_prefix()':
/opt/ohpc/pub/libs/intel/openmpi4/boost/1.71.0/include/boost/regex/v4/perl_matcher_common.hpp:346: undefined reference to `boost::match_results<wchar_t const*, std::allocator<boost::sub_match<wchar_t const*> > >::maybe_assign(boost::match_results<wchar_t const*, std::allocator<boost::sub_match<wchar_t const*> > > const&)'
/opt/ohpc/pub/libs/intel/openmpi4/boost/1.71.0/include/boost/regex/v4/perl_matcher_common.hpp:346: undefined reference to `boost::match_results<wchar_t const*, std::allocator<boost::sub_match<wchar_t const*> > >::maybe_assign(boost::match_results<wchar_t const*, std::allocator<boost::sub_match<wchar_t const*> > > const&)'
/opt/ohpc/pub/libs/intel/openmpi4/boost/1.71.0/include/boost/regex/v4/perl_matcher_common.hpp:346: undefined reference to `boost::match_results<wchar_t const*, std::allocator<boost::sub_match<wchar_t const*> > >::maybe_assign(boost::match_results<wchar_t const*, std::allocator<boost::sub_match<wchar_t const*> > > const&)'
/opt/ohpc/pub/libs/intel/openmpi4/boost/1.71.0/include/boost/regex/v4/perl_matcher_common.hpp:346: undefined reference to `boost::match_results<wchar_t const*, std::allocator<boost::sub_match<wchar_t const*> > >::maybe_assign(boost::match_results<wchar_t const*, std::allocator<boost::sub_match<wchar_t const*> > > const&)'
/opt/ohpc/pub/libs/intel/openmpi4/boost/1.71.0/include/boost/regex/v4/perl_matcher_common.hpp:346: undefined reference to `boost::match_results<wchar_t const*, std::allocator<boost::sub_match<wchar_t const*> > >::maybe_assign(boost::match_results<wchar_t const*, std::allocator<boost::sub_match<wchar_t const*> > > const&)'
/tmp/icpcbunIMt.o:/opt/ohpc/pub/libs/intel/openmpi4/boost/1.71.0/include/boost/regex/v4/perl_matcher_common.hpp:346: more undefined references to `boost::match_results<wchar_t const*, std::allocator<boost::sub_match<wchar_t const*> > >::maybe_assign(boost::match_results<wchar_t const*, std::allocator<boost::sub_match<wchar_t const*> > > const&)' follow
/tmp/icpcbunIMt.o: In function `boost::cpp_regex_traits<wchar_t>::transform[abi:cxx11](wchar_t const*, wchar_t const*) const':
/opt/ohpc/pub/libs/intel/openmpi4/boost/1.71.0/include/boost/regex/v4/cpp_regex_traits.hpp:962: undefined reference to `boost::re_detail_107100::cpp_regex_traits_implementation<wchar_t>::transform[abi:cxx11](wchar_t const*, wchar_t const*) const'
/tmp/icpcbunIMt.o: In function `boost::cpp_regex_traits<wchar_t>::transform_primary[abi:cxx11](wchar_t const*, wchar_t const*) const':
/opt/ohpc/pub/libs/intel/openmpi4/boost/1.71.0/include/boost/regex/v4/cpp_regex_traits.hpp:966: undefined reference to `boost::re_detail_107100::cpp_regex_traits_implementation<wchar_t>::transform_primary[abi:cxx11](wchar_t const*, wchar_t const*) const'
```

**Comment by jcsiadal** [comment]
The current implementation of handling impi wrappers isn't correct. The main mpi compiler binary uses argv[0] to determine which compiler to call, so a softlink from mpicc to mpiicc will always use the gcc compiler, just like calling mpicc directly.

In general, an OSS project shouldn't be writing into commercial software installations.

I'm working on IMB and it's very fussy about wrappers being set correctly. Even with gcc/mpich, CXX must point to mpich mpicc or it will fail to build. I can't see anywhere that this is set in macros or modules.

With the approval of ohpc_cc, ohpc_cxx, etc, configuration should be moved into either ohpc_seetup_mpi, or into the individual lmods. I'd be happy to get a PR in right away; just need to figure out where the config should go.

**Comment by koomie** [comment]
gcc: 

```
[test@sms001 ~]$ module list

Currently Loaded Modules:
  1) autotools   2) prun/2.0   3) gnu9/9.2.0   4) openmpi4/4.0.3   5) ohpc

[test@sms001 ~]$ mpicc -show
gcc -I/opt/ohpc/pub/mpi/openmpi4-gnu9/4.0.3/include -pthread -Wl,-rpath -Wl,/opt/ohpc/pub/mpi/openmpi4-gnu9/4.0.3/lib -Wl,--enable-new-dtags -L/opt/ohpc/pub/mpi/openmpi4-gnu9/4.0.3/lib -lmpi

```

intel:

```
[test@sms001 ~]$ module swap gnu9 intel

The following have been reloaded with a version change:
  1) openmpi4/4.0.3 => openmpi4/4.0.2

[test@sms001 ~]$ mpicc -show
icc -I/opt/ohpc/pub/mpi/openmpi4-intel/4.0.2/include -pthread -Wl,-rpath -Wl,/opt/ohpc/pub/mpi/openmpi4-intel/4.0.2/lib -Wl,--enable-new-dtags -L/opt/ohpc/pub/mpi/openmpi4-intel/4.0.2/lib -lmpi
```

**Comment by jcsiadal** [comment]
Finally have boost building with Intel v19 compiler without using the nextgen switch. Still a fair amount of cleanup to go, then testing on OpenSUSE.

Update will be a fair amount of changes from this pull request, so I'm closing.

**Pull request closed without merging**
